import { Product, GardenProduct, ServicePackage, CategoryMeta } from "./types";

export const categoryMeta: Record<string, CategoryMeta> = {
  indoor: {
    slug: "indoor",
    label: "Indoor Plants",
    description:
      "Curated botanicals to bring life, elegance and cleaner air into every interior space.",
    image: "/images/peace-lily.webp",
    subcategories: [
      { slug: "all", label: "All Indoor" },
      { slug: "air-purifying", label: "Air Purifying" },
      { slug: "low-light", label: "Low Light" },
      { slug: "succulents", label: "Succulents & Cacti" },
      { slug: "herbs", label: "Herbs & Edibles" },
      { slug: "flowering", label: "Flowering" },
    ],
  },
  outdoor: {
    slug: "outdoor",
    label: "Outdoor Plants",
    description:
      "Hardy, vibrant specimens to transform your garden, terrace or outdoor living space.",
    image: "/images/garden-two.webp",
    subcategories: [
      { slug: "all", label: "All Outdoor" },
      { slug: "flowers", label: "Garden Flowers" },
      { slug: "shrubs", label: "Shrubs & Hedges" },
      { slug: "climbing", label: "Climbing Plants" },
      { slug: "ornamental", label: "Ornamental" },
    ],
  },
  fruit: {
    slug: "fruit",
    label: "Fruit Plants",
    description:
      "From mango to citrus — fruit-bearing trees and plants that reward patience with abundance.",
    image: "/images/mango-tree.jpg",
    subcategories: [
      { slug: "all", label: "All Fruit" },
      { slug: "tropical", label: "Tropical" },
      { slug: "citrus", label: "Citrus" },
      { slug: "dwarf", label: "Dwarf Varieties" },
    ],
  },
};

export const products: Product[] = [
  // ─── INDOOR ───────────────────────────────────────────────────────────
  {
    id: "p1",
    name: "Snake Plant",
    slug: "snake-plant",
    description: "One of the hardiest houseplants available — thrives on neglect.",
    longDescription:
      "Sansevieria trifasciata is a celebrated air purifier and architectural specimen. Its upright, sword-like leaves require minimal watering and tolerate low light, making it the ideal choice for busy interiors.",
    price: 5500,
    originalPrice: 6500,
    image: "/images/snake-plant.jpg",
    category: "indoor",
    subcategory: "air-purifying",
    tags: ["air-purifying", "low-light", "drought-tolerant"],
    careLevel: "easy",
    light: "low",
    water: "Every 2–3 weeks",
    badge: "bestseller",
    inStock: true,
    sizes: [
      { label: "Small (20cm)", price: 5500 },
      { label: "Medium (40cm)", price: 8500 },
    ],
  },
  {
    id: "p2",
    name: "Peace Lily",
    slug: "peace-lily",
    description: "An elegant, white-blooming classic for homes and offices.",
    price: 7200,
    image: "/images/peace-lily.webp",
    category: "indoor",
    subcategory: "flowering",
    tags: ["flowering", "air-purifying", "medium-light"],
    careLevel: "medium",
    light: "medium",
    water: "Weekly",
    inStock: true,
    sizes: [
      { label: "Medium (30cm)", price: 7200 },
      { label: "Large (50cm)", price: 12000 },
    ],
  },
  {
    id: "p3",
    name: "Spider Plant",
    slug: "spider-plant",
    description: "Fast-growing, pet-friendly and effortlessly beautiful.",
    price: 4800,
    image: "/images/spider-plant.webp",
    category: "indoor",
    subcategory: "air-purifying",
    tags: ["air-purifying", "pet-friendly", "low-light"],
    careLevel: "easy",
    light: "medium",
    water: "When top soil dries",
    badge: "featured",
    inStock: true,
  },
  {
    id: "p4",
    name: "ZZ Plant",
    slug: "zz-plant",
    description: "Glossy, architectural foliage — virtually indestructible.",
    price: 3500,
    image: "/images/zz-plant.webp",
    category: "indoor",
    subcategory: "low-light",
    tags: ["low-light", "drought-tolerant", "air-purifying"],
    careLevel: "easy",
    light: "low",
    water: "Every 3–4 weeks",
    badge: "bestseller",
    inStock: true,
  },
  {
    id: "p5",
    name: "Monstera Deliciosa",
    slug: "monstera-deliciosa",
    description: "The iconic split-leaf statement plant for any interior.",
    price: 12500,
    image: "/images/garden-two.webp",
    category: "indoor",
    subcategory: "low-light",
    tags: ["statement", "air-purifying", "tropical"],
    careLevel: "medium",
    light: "medium",
    water: "Weekly",
    badge: "new",
    inStock: true,
    sizes: [
      { label: "Medium (50cm)", price: 12500 },
      { label: "Large (80cm)", price: 22000 },
    ],
  },
  {
    id: "p6",
    name: "Pothos Golden",
    slug: "pothos-golden",
    description: "Trailing vines with golden-green variegation — irresistibly versatile.",
    price: 3200,
    image: "/images/basil.webp",
    category: "indoor",
    subcategory: "low-light",
    tags: ["trailing", "low-light", "air-purifying", "pet-friendly"],
    careLevel: "easy",
    light: "low",
    water: "When top soil dries",
    inStock: true,
  },
  {
    id: "p7",
    name: "Basil",
    slug: "basil",
    description: "Aromatic culinary herb — fresh from garden to kitchen.",
    price: 2500,
    image: "/images/basil.webp",
    category: "indoor",
    subcategory: "herbs",
    tags: ["edible", "herb", "aromatic"],
    careLevel: "easy",
    light: "bright",
    water: "Keep moist",
    badge: "new",
    inStock: true,
  },
  {
    id: "p8",
    name: "Aloe Vera",
    slug: "aloe-vera",
    description: "Timeless medicinal succulent — beautiful and practical.",
    price: 2800,
    image: "/images/zz-plant.webp",
    category: "indoor",
    subcategory: "succulents",
    tags: ["succulent", "medicinal", "drought-tolerant"],
    careLevel: "easy",
    light: "bright",
    water: "Every 2–3 weeks",
    inStock: true,
  },

  // ─── OUTDOOR ──────────────────────────────────────────────────────────
  {
    id: "p9",
    name: "Rose Bush",
    slug: "rose-bush",
    description: "Classic garden romance — blooms repeatedly through the season.",
    price: 6800,
    originalPrice: 8500,
    image: "/images/rose-bush.webp",
    category: "outdoor",
    subcategory: "flowers",
    tags: ["flowering", "fragrant", "garden"],
    careLevel: "hard",
    light: "bright",
    water: "2–3 times weekly",
    badge: "sale",
    inStock: true,
  },
  {
    id: "p10",
    name: "Hibiscus",
    slug: "hibiscus",
    description: "Bold tropical blooms in vivid red — a garden showstopper.",
    price: 4500,
    originalPrice: 6000,
    image: "/images/hibiscus.jpg",
    category: "outdoor",
    subcategory: "shrubs",
    tags: ["flowering", "tropical", "shrub"],
    careLevel: "medium",
    light: "bright",
    water: "Regularly",
    badge: "sale",
    inStock: true,
  },
  {
    id: "p11",
    name: "Bougainvillea",
    slug: "bougainvillea",
    description: "Vivid cascading bracts in pink and purple — perfect for walls and fences.",
    price: 3800,
    originalPrice: 5500,
    image: "/images/bougainvillea.webp",
    category: "outdoor",
    subcategory: "climbing",
    tags: ["climbing", "flowering", "drought-tolerant"],
    careLevel: "medium",
    light: "bright",
    water: "Moderately",
    badge: "sale",
    inStock: true,
  },
  {
    id: "p12",
    name: "Sunflower",
    slug: "sunflower",
    description: "Cheerful annual that follows the sun — uplifting in any garden.",
    price: 2500,
    originalPrice: 3500,
    image: "/images/sunflower.webp",
    category: "outdoor",
    subcategory: "flowers",
    tags: ["annual", "bright", "easy"],
    careLevel: "easy",
    light: "bright",
    water: "Regularly",
    inStock: true,
  },
  {
    id: "p13",
    name: "Zinnia",
    slug: "zinnia",
    description: "Prolific, easy-care blooms in a spectrum of colour from summer to frost.",
    price: 1800,
    originalPrice: 2500,
    image: "/images/zinnia.webp",
    category: "outdoor",
    subcategory: "flowers",
    tags: ["annual", "colorful", "easy"],
    careLevel: "easy",
    light: "bright",
    water: "Regularly",
    badge: "sale",
    inStock: true,
  },
  {
    id: "p14",
    name: "Ixora",
    slug: "ixora",
    description: "Dense clusters of star-shaped flowers — exceptional as a hedge or specimen.",
    price: 3200,
    image: "/images/hibiscus.jpg",
    category: "outdoor",
    subcategory: "shrubs",
    tags: ["flowering", "hedge", "tropical"],
    careLevel: "medium",
    light: "bright",
    water: "Regularly",
    badge: "new",
    inStock: true,
  },
  {
    id: "p15",
    name: "Croton",
    slug: "croton",
    description: "Spectacular multi-coloured foliage — a living work of art for warm gardens.",
    price: 4500,
    image: "/images/bougainvillea.webp",
    category: "outdoor",
    subcategory: "ornamental",
    tags: ["foliage", "colorful", "tropical"],
    careLevel: "medium",
    light: "bright",
    water: "Moderately",
    inStock: true,
  },

  // ─── FRUIT ────────────────────────────────────────────────────────────
  {
    id: "p16",
    name: "Mango Tree",
    slug: "mango-tree",
    description: "Nigeria's beloved fruit tree — prolific, sweet-fruited and shade-giving.",
    price: 15000,
    image: "/images/mango-tree.jpg",
    category: "fruit",
    subcategory: "tropical",
    tags: ["fruit-bearing", "shade", "tropical"],
    careLevel: "medium",
    light: "bright",
    water: "Deeply weekly",
    badge: "featured",
    inStock: true,
    sizes: [
      { label: "Seedling (60cm)", price: 15000 },
      { label: "Grafted (1m)", price: 28000 },
    ],
  },
  {
    id: "p17",
    name: "Lemon Tree",
    slug: "lemon-tree",
    description: "Fragrant blossom, year-round fruit — a Mediterranean classic for warm climates.",
    price: 12000,
    image: "/images/lemon-tree.webp",
    category: "fruit",
    subcategory: "citrus",
    tags: ["citrus", "fragrant", "fruit-bearing"],
    careLevel: "medium",
    light: "bright",
    water: "2–3 times weekly",
    badge: "new",
    inStock: true,
    sizes: [
      { label: "Small (50cm)", price: 12000 },
      { label: "Medium (80cm)", price: 18000 },
    ],
  },
  {
    id: "p18",
    name: "Orange Tree",
    slug: "orange-tree",
    description: "Sweet, juicy oranges — a rewarding tree for any sunny garden.",
    price: 13500,
    image: "/images/lemon-tree.webp",
    category: "fruit",
    subcategory: "citrus",
    tags: ["citrus", "fruit-bearing", "fragrant"],
    careLevel: "medium",
    light: "bright",
    water: "2–3 times weekly",
    inStock: true,
  },
  {
    id: "p19",
    name: "Pawpaw (Papaya)",
    slug: "pawpaw",
    description: "Fast-maturing tropical fruit tree — harvests within a year of planting.",
    price: 5500,
    image: "/images/mango-tree.jpg",
    category: "fruit",
    subcategory: "tropical",
    tags: ["fast-growing", "tropical", "fruit-bearing"],
    careLevel: "easy",
    light: "bright",
    water: "Regularly",
    inStock: true,
  },
  {
    id: "p20",
    name: "Avocado",
    slug: "avocado",
    description: "Nutritious, buttery fruit from a handsome, shade-providing tree.",
    price: 10000,
    image: "/images/mango-tree.jpg",
    category: "fruit",
    subcategory: "tropical",
    tags: ["tropical", "nutritious", "fruit-bearing"],
    careLevel: "medium",
    light: "bright",
    water: "Weekly",
    badge: "new",
    inStock: true,
  },
  {
    id: "p21",
    name: "Dwarf Banana",
    slug: "dwarf-banana",
    description: "Compact, ornamental and fruit-bearing — ideal for gardens and large pots.",
    price: 7500,
    image: "/images/mango-tree.jpg",
    category: "fruit",
    subcategory: "dwarf",
    tags: ["dwarf", "tropical", "fruit-bearing"],
    careLevel: "easy",
    light: "bright",
    water: "Regularly",
    inStock: true,
  },
  {
    id: "p22",
    name: "Guava Tree",
    slug: "guava-tree",
    description: "Fragrant, prolific and intensely flavoured — a garden staple across West Africa.",
    price: 9000,
    image: "/images/mango-tree.jpg",
    category: "fruit",
    subcategory: "tropical",
    tags: ["tropical", "fragrant", "fruit-bearing"],
    careLevel: "easy",
    light: "bright",
    water: "Weekly",
    inStock: true,
  },
];

export const gardenProducts: GardenProduct[] = [
  {
    id: "g1",
    name: "Premium Potting Mix",
    slug: "premium-potting-mix",
    description: "Nutrient-rich, free-draining mix formulated for containers and beds.",
    price: 3500,
    image: "/images/garden-two.webp",
    subcategory: "soil",
    badge: "bestseller",
  },
  {
    id: "g2",
    name: "Organic Compost (20L)",
    slug: "organic-compost",
    description: "Cold-process compost to condition and enrich any garden soil.",
    price: 2800,
    image: "/images/garden-two.webp",
    subcategory: "soil",
  },
  {
    id: "g3",
    name: "Terracotta Pot Set (3 sizes)",
    slug: "terracotta-pot-set",
    description: "Handcrafted Italian-style terracotta in three graduated sizes.",
    price: 8500,
    originalPrice: 11000,
    image: "/images/balcony-garden.png",
    subcategory: "pots",
    badge: "sale",
  },
  {
    id: "g4",
    name: "White Ceramic Planter",
    slug: "white-ceramic-planter",
    description: "Minimal European-style planter with drainage hole — 25cm diameter.",
    price: 4200,
    image: "/images/balcony-garden.png",
    subcategory: "pots",
    badge: "new",
  },
  {
    id: "g5",
    name: "Garden Trowel & Fork Set",
    slug: "trowel-fork-set",
    description: "Stainless steel tools with solid beechwood handles. Lifetime quality.",
    price: 5500,
    image: "/images/formal-garden.jpg",
    subcategory: "tools",
  },
  {
    id: "g6",
    name: "Slow-Release Fertiliser",
    slug: "slow-release-fertiliser",
    description: "6-month granular feed for healthy, sustained plant growth.",
    price: 2200,
    image: "/images/formal-garden.jpg",
    subcategory: "fertilisers",
    badge: "bestseller",
  },
  {
    id: "g7",
    name: "Heirloom Vegetable Seeds Pack",
    slug: "vegetable-seeds",
    description: "Curated selection of 10 heirloom vegetable varieties suited to Nigerian climate.",
    price: 1800,
    image: "/images/basil.webp",
    subcategory: "seeds",
    badge: "new",
  },
  {
    id: "g8",
    name: "Watering Can (5L, Brass Rose)",
    slug: "watering-can",
    description: "French galvanized steel can with detachable brass rose — elegant and practical.",
    price: 7200,
    image: "/images/formal-garden.jpg",
    subcategory: "tools",
  },
];

export const services: ServicePackage[] = [
  // ─── GARDEN NEEDS SERVICES ────────────────────────────────────────────
  {
    id: "s1",
    name: "Plant Selection Consultation",
    slug: "plant-consultation",
    description:
      "A 1-hour consultation with one of our horticulturists to curate the right plants for your space, light conditions and lifestyle.",
    price: 8000,
    priceNote: "per session",
    features: [
      "1-hour in-person or virtual session",
      "Space and light assessment",
      "Personalised plant shortlist (up to 10)",
      "Written care guide provided",
    ],
    duration: "1 hour",
    category: "garden-needs",
    subcategory: "consultation",
  },
  {
    id: "s2",
    name: "Soil Analysis & Preparation",
    slug: "soil-analysis",
    description:
      "Complete soil testing and amendment service to prepare your beds for healthy, productive planting.",
    price: 15000,
    priceNote: "per plot (up to 20 sqm)",
    features: [
      "Full pH and nutrient analysis",
      "Soil amendment recommendations",
      "Manual soil preparation",
      "Organic compost incorporation",
    ],
    duration: "Half day",
    category: "garden-needs",
    subcategory: "soil",
  },
  {
    id: "s3",
    name: "Pot & Planter Setup",
    slug: "planter-setup",
    description:
      "We source, fill and arrange pots and planters for balconies, terraces and indoor spaces.",
    price: 25000,
    priceNote: "from",
    features: [
      "Container selection and sourcing",
      "Premium potting mix filling",
      "Plant installation",
      "Care instructions handover",
    ],
    category: "garden-needs",
    subcategory: "installation",
    featured: true,
  },

  // ─── LANDSCAPING SERVICES ─────────────────────────────────────────────
  {
    id: "s4",
    name: "Garden Design Consultation",
    slug: "garden-design",
    description:
      "A comprehensive design consultation yielding a full planting plan, material palette and phased implementation schedule.",
    price: 35000,
    priceNote: "per project",
    features: [
      "Site survey and measurements",
      "Mood board & concept design",
      "Full planting scheme (CAD plan)",
      "Material and supplier recommendations",
      "2 revision rounds included",
    ],
    duration: "3–5 days",
    category: "landscaping",
    subcategory: "design",
  },
  {
    id: "s5",
    name: "Full Garden Installation",
    slug: "full-installation",
    description:
      "End-to-end garden build — from ground preparation and irrigation to final planting and styling.",
    price: 120000,
    priceNote: "from (up to 50 sqm)",
    features: [
      "Full ground clearance & levelling",
      "Soil enrichment",
      "Irrigation system installation",
      "All plants and materials supplied",
      "Professional installation",
      "30-day aftercare warranty",
    ],
    duration: "3–7 days",
    category: "landscaping",
    subcategory: "installation",
    featured: true,
  },
  {
    id: "s6",
    name: "Monthly Maintenance Plan",
    slug: "monthly-maintenance",
    description:
      "Ongoing garden care to keep your outdoor space looking its finest through every season.",
    price: 18000,
    priceNote: "per month",
    features: [
      "2 visits per month",
      "Pruning, weeding & edging",
      "Fertilising and pest checks",
      "Lawn mowing (if applicable)",
      "Monthly condition report",
    ],
    category: "landscaping",
    subcategory: "maintenance",
  },
  {
    id: "s7",
    name: "Lawn Renovation",
    slug: "lawn-renovation",
    description:
      "Complete lawn assessment, scarification, overseeding and top-dressing for a lush, even sward.",
    price: 45000,
    priceNote: "up to 100 sqm",
    features: [
      "Lawn condition assessment",
      "Scarification & aeration",
      "Overseeding with premium turf mix",
      "Top-dressing application",
      "4-week follow-up check",
    ],
    category: "landscaping",
    subcategory: "lawn",
  },
  {
    id: "s8",
    name: "Irrigation System Installation",
    slug: "irrigation",
    description:
      "Smart drip or sprinkler irrigation — installed, programmed and calibrated for your garden.",
    price: 55000,
    priceNote: "from",
    features: [
      "Water requirements assessment",
      "System design & pipe layout",
      "Professional installation",
      "Timer and controller programming",
      "1-year parts warranty",
    ],
    category: "landscaping",
    subcategory: "irrigation",
  },
];

export const gardenNeedsMeta = {
  slug: "garden-needs",
  label: "Garden Needs & Services",
  description:
    "Premium tools, soils, planters and expert services — everything needed to nurture a thriving garden.",
  image: "/images/formal-garden.jpg",
  subcategories: [
    { slug: "all", label: "All" },
    { slug: "soil", label: "Soil & Compost" },
    { slug: "tools", label: "Tools & Equipment" },
    { slug: "pots", label: "Pots & Planters" },
    { slug: "fertilisers", label: "Fertilisers" },
    { slug: "seeds", label: "Seeds & Bulbs" },
    { slug: "services", label: "Our Services" },
  ],
};

export const landscapingMeta = {
  slug: "landscaping",
  label: "Landscaping & Maintenance",
  description:
    "Professional garden design, installation and maintenance by certified horticulturists.",
  image: "/images/formal-garden.jpg",
  subcategories: [
    { slug: "all", label: "All Services" },
    { slug: "design", label: "Garden Design" },
    { slug: "installation", label: "Installation" },
    { slug: "maintenance", label: "Maintenance" },
    { slug: "lawn", label: "Lawn Care" },
    { slug: "irrigation", label: "Irrigation" },
  ],
};

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductsBySubcategory(
  category: string,
  subcategory: string
): Product[] {
  if (subcategory === "all") return getProductsByCategory(category);
  return products.filter(
    (p) => p.category === category && p.subcategory === subcategory
  );
}

export function getServicesByCategory(category: string): ServicePackage[] {
  return services.filter((s) => s.category === category);
}

export function formatPrice(price: number): string {
  return `₦${price.toLocaleString("en-NG")}`;
}
